### ISSUE TITLE
it's not an issue it's a solution

### ISSUE THREAD

**Issue by Landaes** [boblemarin/jQuery.eraser#14]
In line 98 do this: ctx.drawImage(that, 0, 0, width, height);
and in line 326 this: data.ctx.drawImage( data.source, 0, 0 , data.w, data.h);

fix an issue in devices whith other devicePixelRatio but 1 (like he new iPad)

Ok, i'm gonna write this in spanish, just because my shitty english: En la lína 98 pega esto:ctx.drawImage(that, 0, 0, width, height); y en la línea 326 esto: data.ctx.drawImage( data.source, 0, 0 , data.w, data.h);

Arregla un problema en los dispositivos que tienen un devicePixelRatio distinto de 1 (como el nuevo iPad)

**Comment by boblemarin** [comment]
Thanks, I added your fix in the library.
