### ISSUE TITLE
Callback function

### ISSUE THREAD

**Issue by shawnier** [boblemarin/jQuery.eraser#2]
Hi 

Firstable I would like to say thanks for this great plugin. Everything works perfectly for my purpose and it does seems like the besteraser (scratch)plugin available online.

I have been trying to get the callback function working.

however the function is called when the document is loaded. ( instead of being calledback when the eraser function complete).

function test() {
                    $('#test').fadeIn();
                }
                function init(event) {
                    $("#redux").eraser({
                        completeRatio: 0.8,
                        completeFunction: test()
                    });
                }
                addEventListener( "load", init, false );

**Comment by chuck59** [comment]
I'm facing the same issue, can you please assist how did you fix? btw I've removed () from completeFunction: test() line
