### ISSUE TITLE
android default browser erase issue

### ISSUE THREAD

**Issue by RandevM** [boblemarin/jQuery.eraser#4]
HI, 

First of all - great script, does exactly what I was looking for. 

I have noticed in default android browser (tested with samsung s3 & galaxy tab running android 4.1.1- 4.2) the erase function doesn't work as expected. 

I have hooked up a callback (which fires) but the panel doesn't erase. 
Works fine in Chrome for android. 

Any idea why this is happening?

**Comment by jcpplus** [comment]
samsung s5 has the same proplem with android 4.2.2 :(
